openapi: "3.0.0"

info:
  title: API Endpoints for Serving Machine Learning Models
  version: "1.0.0"

servers:
  - url: "/"

paths:
  /models/irisClassifier:
    put:
      summary: Predict Iris Species
      operationId: models.irisClassifier
      x-body-name: body
      tags:
        - models
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [sepal_length, sepal_width, petal_length, petal_width]
              properties:
                sepal_length: { type: number }
                sepal_width: { type: number }
                petal_length: { type: number }
                petal_width: { type: number }
      responses:
        "200":
          description: Successful Prediction
        "500":
          description: Server Error

  /models/shapesClassifier:
    put:
      summary: Predict Shape from Image
      operationId: models.shapesClassifier
      tags:
        - models
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [image]
              properties:
                image:
                  type: string
                  format: binary
      responses:
        "200":
          description: Successful Prediction
        "500":
          description: Server Error
