openapi: "3.0.0"

info:
  title: API Endpoints for serving Machine Learning Models
  description: API Endpoints for serving Machine Learning Models
  version: "1.0.0"

servers:
  - url: "http://localhost:8000/api"

paths:
  /models/irisClassifier:
    put:
      summary: Use the Iris flower classifier model to make a prediction
      operationId: app_api.src.models.irisClassifier
      tags:
        - models
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [sepal_length, sepal_width, petal_length, petal_width]
              properties:
                sepal_length:
                  type: number
                  description: Sepal length
                sepal_width:
                  type: number
                  description: Sepal width
                petal_length:
                  type: number
                  description: Petal length
                petal_width:
                  type: number
                  description: Petal width
      responses:
        "200":
          description: Prediction successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  prediction:
                    type: string
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid input data provided

  /models/shapesClassifier:
    put:
      summary: Use the Shapes classifier model to make a prediction
      operationId: app_api.src.models.shapesClassifier
      tags:
        - models
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [image]
              properties:
                image:
                  type: string
                  format: binary
                  description: Image file to classify
      responses:
        "200":
          description: Prediction successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  prediction:
                    type: string
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid input data provided
